project_id = "ctkozjqdvhtvabxhxlth"

[functions.admin-create-user]
verify_jwt = false

[functions.opex-reminder]
verify_jwt = false

[functions.send-meeting-invitation]
verify_jwt = false

[functions.send-signature-request]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.generate-report]
verify_jwt = false
